version: "2"

services:
  ui:
    image: ghcr.io/maggie0002/bdu:latest
    network_mode: host
    labels:
      io.balena.features.supervisor-api: "1"
      io.balena.features.balena-api: "1"

  grafana:
    image: ghcr.io/volkovlabs/app:latest
    network_mode: host
    restart: always
    labels:
      io.balena.features.supervisor-api: "1"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
